CREATE TABLE COMPANY(
    COMPANY_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    COMPANY_NAME VARCHAR(128) NOT NULL UNIQUE,
    EMAIL VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(128) NOT NULL,
	FOREIGN KEY(EMAIL) REFERENCES USER(EMAIL)

);


CREATE TABLE OUTSIDE_HIRED_EMPLOYEE(
	EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
	COMPANY_ID VARCHAR(64),
    FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(COMPANY_ID)

);
