CREATE TABLE SPOILAGE_AGENT_TYPE(
	SPOILAGE_AGENT_TYPE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VALUE  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SPOILAGE_AGENT(
	SPOILAGE_AGENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    TYPE INT NOT NULL,
    FOREIGN KEY(TYPE) REFERENCES SPOILAGE_AGENT_TYPE(SPOILAGE_AGENT_TYPE_ID)
);
