CREATE TABLE STATUS(
    STATUS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VALUE  VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE SUPERVISION(
	SUPERVISION_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    THEATRE_GOOD_ID INT,
    FOREIGN KEY(THEATRE_GOOD_ID) REFERENCES THEATRE_GOOD(THEATRE_GOOD_ID),
    ID_NUMBER VARCHAR(25),
    FOREIGN KEY(ID_NUMBER) REFERENCES USER(ID_NUMBER),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    EXECUTION_DATE DATE,
    ACTION_ID INT,
	FOREIGN KEY(ACTION_ID) REFERENCES ACTIONS(ACTION_ID)
);


CREATE TABLE PDF(
	PDF_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VALUE  VARCHAR(150) NOT NULL,
    SUPERVISION_ID INT NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    FOREIGN KEY(SUPERVISION_ID) REFERENCES SUPERVISION(SUPERVISION_ID)
);


CREATE TABLE SUPERVISION_CHANGE_LOG(
    SUPERVISION_CHANGE_LOG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LAST_CHANGE_ID_NUMBER VARCHAR(25) NOT NULL,
    FOREIGN KEY(LAST_CHANGE_ID_NUMBER) REFERENCES USER(ID_NUMBER),
    LAST_CHANGE_DATE DATE NOT NULL,
    SUPERVISION_ID INT NOT NULL,
    FOREIGN KEY(SUPERVISION_ID) REFERENCES SUPERVISION(SUPERVISION_ID)
);

# DELIMITER $$
#
# CREATE TRIGGER AFTER_DELETE_TT
#     BEFORE DELETE ON THEATRE_GOOD FOR EACH ROW
#     BEGIN
#        DELETE FROM SUPERVISION WHERE THEATRE_GOOD_ID = OLD.THEATRE_GOOD_ID;
#     END$$
#
# DELIMITER ;

# DROP TRIGGER  AFTER_DELETE_TT;

DELIMITER $$

CREATE TRIGGER BEFORE_DELETE_SUPERVISION
    BEFORE DELETE ON SUPERVISION FOR EACH ROW
    BEGIN
       DELETE FROM SUPERVISION_CHANGE_LOG WHERE SUPERVISION_CHANGE_LOG.SUPERVISION_ID = OLD.SUPERVISION_ID;
       DELETE FROM PDF WHERE PDF.SUPERVISION_ID = OLD.SUPERVISION_ID;
    END$$

DELIMITER ;